services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  web:
    restart: always
    build:
      context: ./
      dockerfile: ./dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis